---
modules:
  http_relay:
    fork: ./http_relay.py --static /=public
    accepts: jsonl
    # modules allowed to be called via http relay
    uses:
    - mycalc
    - book
    - db
  http_admin_relay:
    fork: ./http_relay.py --port 5000 --basic-auth YWRtaW46YWRtaW4= --static /=public_admin
    accepts: jsonl
    # modules allowed to be called via http relay
    uses:
    - _admin
  db:
    fork: ./db_relay.py
    accepts: jsonl
    # this is the opposite of uses
    only_from:
    - book
    - http_relay
  mycalc:
    fork: ./mycalc.py
    accepts: jsonl
  book:
    fork: ./book.py
    accepts: jsonl
    uses:
    - db
  periodic:
    fork: ./periodic.py
    accepts: jsonl
    uses:
    - mycalc
