---
modules:
  http_relay:
    fork: ./http_relay.py
    accepts: jsonl
    # modules allowed to be called via http relay
    uses:
    - mycalc
    - book
  db:
    fork: ./db_relay.py
    accepts: jsonl
    # this is the opposite of uses
    only_from:
    - book
  mycalc:
    fork: ./mycalc.py
    accepts: jsonl
  book:
    fork: ./book.py
    accepts: jsonl
    uses:
    - db
  periodic:
    fork: ./periodic.py
    accepts: jsonl
    uses:
    - mycalc
